export const COLUMN_LIST = [
  {
    column: 'school_year_format',
    label: 'menu.schoolYear',
    width: '15%',
    translate: false,
    badge: false,
    color: '',
    textCenter: false,
  },
  {
    column: 'academic_period_format',
    label: 'forms.academicPeriod',
    width: '15%',
    translate: false,
    badge: false,
    color: '',
    textCenter: false,
  },
  {
    column: 'startDate',
    label: 'forms.startDate',
    width: '10%',
    translate: false,
    badge: false,
    color: '',
    textCenter: false,
  },
  {
    column: 'endDate',
    label: 'forms.endDate',
    width: '10%',
    translate: false,
    badge: false,
    color: '',
    textCenter: false,
  },
  {
    column: 'active',
    label: 'forms.active',
    width: '10%',
    translate: true,
    badge: true,
    color: 'info',
    textCenter: false,
  },
  {
    column: '',
    label: 'pages.actions',
    width: '30%',
    translate: true,
    badge: false,
    color: '',
    textCenter: false,
  },
];
